package com.cyrev.iam.entra.service.onboarding;

import com.cyrev.common.entities.TenantContext;
import com.cyrev.common.entities.TenantContextHolder;
import com.cyrev.iam.config.EntraProperties;
import com.cyrev.iam.entra.service.clients.ResilientExchangeClient;
import com.cyrev.iam.entra.service.clients.ResilientGraphClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import java.util.List;
import java.util.Map;

/**
 * Generates the one-time Exchange Online RBAC setup script for a tenant's admin to
 * run themselves via Connect-ExchangeOnline.
 *
 * We previously tried to run New-ServicePrincipal/New-ManagementRoleAssignment
 * programmatically using the consenting admin's own delegated OAuth token, on the
 * theory that Exchange Online's REST InvokeCommand surface would honor the admin's
 * real RBAC privilege the same way it does for an interactive PowerShell session.
 * Verified against a real tenant that this doesn't work: even with a correctly
 * audienced delegated token (aud=outlook.office365.com), Azure AD only ever issues
 * scp=User.Read for third-party app registrations against this resource — there is
 * no delegated permission a third-party app can be granted that's strong enough to
 * run RBAC/service-principal-management cmdlets. That capability is hard-wired to
 * Microsoft's own first-party Exchange Online PowerShell client. So instead of
 * executing the cmdlets ourselves, we generate them (with the real AppId/ObjectId
 * filled in) for the admin to run once, in a session that does carry real privilege.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ExchangeBootstrapService {

    private static final String ROLE_NAME = "Mail Recipients";

    // Built-in Microsoft Entra role template id for "Exchange Administrator".
    private static final String EXCHANGE_ADMINISTRATOR_ROLE_ID = "29232cdf-9323-42fd-ade2-1d097af3e4de";

    private final EntraProperties props;
    private final ResilientGraphClient resilientGraphClient;
    private final ResilientExchangeClient resilientExchangeClient;

    /**
     * Self-assigns the Exchange Administrator directory role to our own service principal
     * in the consenting tenant, using the RoleManagement.ReadWrite.Directory app permission
     * granted during admin consent. Combined with the Exchange.ManageAsApp permission (also
     * granted at consent time), this gives app-only Exchange Online access without requiring
     * the admin to run the manual setup script generated by {@link #generateSetupScript()}.
     */
    public void provisionExchangeAdminRole(String entraTenantId) {
        String spObjectId = lookupServicePrincipalObjectId(entraTenantId);
        if (hasExchangeAdministratorRole(entraTenantId, spObjectId)) {
            log.info("Service principal {} already holds Exchange Administrator role in tenant {}",
                    spObjectId, entraTenantId);
            return;
        }
        resilientGraphClient.post(entraTenantId, "/roleManagement/directory/roleAssignments", Map.of(
                "principalId", spObjectId,
                "roleDefinitionId", EXCHANGE_ADMINISTRATOR_ROLE_ID,
                "directoryScopeId", "/"
        ));
        log.info("Assigned Exchange Administrator role to service principal {} in tenant {}",
                spObjectId, entraTenantId);
    }

    @SuppressWarnings("unchecked")
    private boolean hasExchangeAdministratorRole(String entraTenantId, String spObjectId) {
        Map<String, Object> response = resilientGraphClient.get(
                entraTenantId,
                "/roleManagement/directory/roleAssignments?$filter=principalId eq '" + spObjectId
                        + "' and roleDefinitionId eq '" + EXCHANGE_ADMINISTRATOR_ROLE_ID + "'"
        );
        List<Map<String, Object>> value = (List<Map<String, Object>>) response.get("value");
        return value != null && !value.isEmpty();
    }

    public String generateSetupScript() {
        TenantContext tenant = TenantContextHolder.get();
        String entraTenantId = tenant.getEntraTenantId();
        String spObjectId = lookupServicePrincipalObjectId(entraTenantId);
        return buildScript(entraTenantId, spObjectId);
    }

    /**
     * Probes Exchange Online with the app's own (app-only) client-credentials token —
     * the same one every real Exchange feature in this app uses — to check whether the
     * admin has actually run the setup script yet. A minimal Get-Mailbox call is enough:
     * it 401/403s until the RBAC role assignment from the script has taken effect.
     */
    public boolean verifySetup() {
        TenantContext tenant = TenantContextHolder.get();
        String entraTenantId = tenant.getEntraTenantId();
        try {
            resilientExchangeClient.invokeForList(entraTenantId, "Get-Mailbox", Map.of("ResultSize", "1"));
            return true;
        } catch (WebClientResponseException e) {
            log.warn("Exchange setup verification failed for tenant {}: {}, responseBody={}",
                    entraTenantId, e.getMessage(), e.getResponseBodyAsString());
            return false;
        }
    }

    private String buildScript(String entraTenantId, String spObjectId) {
        return """
                # Run this once in Exchange Online PowerShell as a Global Admin or Exchange
                # Admin for this tenant. Requires the ExchangeOnlineManagement module:
                #   Install-Module -Name ExchangeOnlineManagement

                Connect-ExchangeOnline -Organization "%s"

                New-ServicePrincipal -AppId "%s" -ObjectId "%s" -DisplayName "Cyrev"

                # If the line below is rejected, use this instead:
                #   Add-RoleGroupMember "Organization Management" -Member "%s"
                New-ManagementRoleAssignment -Role "%s" -App "%s"
                """.formatted(
                entraTenantId,
                props.getAppId(), spObjectId,
                spObjectId,
                ROLE_NAME, props.getAppId()
        );
    }

    @SuppressWarnings("unchecked")
    private String lookupServicePrincipalObjectId(String entraTenantId) {
        Map<String, Object> response = resilientGraphClient.get(
                entraTenantId,
                "/servicePrincipals?$filter=appId eq '" + props.getAppId() + "'"
        );
        List<Map<String, Object>> value = (List<Map<String, Object>>) response.get("value");
        if (value == null || value.isEmpty()) {
            throw new IllegalStateException(
                    "No service principal found for appId " + props.getAppId() + " in tenant " + entraTenantId);
        }
        return (String) value.get(0).get("id");
    }
}
